// <auto-generated />
using System;
using Commcare.Integration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commcare.Integration.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230307101358_add_pull_history_table")]
    partial class add_pull_history_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commcare.Integration.Entities.AppDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<string>("AppName")
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.HasKey("Id");

                    b.ToTable("app_list");
                });

            modelBuilder.Entity("Commcare.Integration.Entities.FormData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<string>("FormId")
                        .HasColumnType("text")
                        .HasColumnName("form_id");

                    b.HasKey("Id");

                    b.ToTable("form_data");
                });

            modelBuilder.Entity("Commcare.Integration.Entities.FormDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("FormId")
                        .HasColumnType("text")
                        .HasColumnName("form_id");

                    b.Property<string>("FormLink")
                        .HasColumnType("text")
                        .HasColumnName("form_link");

                    b.Property<string>("QuartNum")
                        .HasColumnType("text")
                        .HasColumnName("quart_num");

                    b.Property<DateTime>("SurveyDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("survey_date");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_end");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_start");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("form_details");
                });

            modelBuilder.Entity("Commcare.Integration.Entities.FormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.HasKey("Id");

                    b.ToTable("form_fields");
                });

            modelBuilder.Entity("Commcare.Integration.Entities.PullHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime>("PullDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pull_date");

                    b.Property<string>("PullStatus")
                        .HasColumnType("text")
                        .HasColumnName("pull_status");

                    b.HasKey("Id");

                    b.ToTable("pull_history");
                });
#pragma warning restore 612, 618
        }
    }
}
